# A richer, more distinct training dataset for better model confidence.

TRAINING_DATA = {
    # --- POSITIVE INTENTS ---
    "open_notepad": [
        "run notepad",
        "open the notepad application",
        "I need a text editor",
        "start a new note",
        "launch notepad",
        "open notepad please",
        "can you open notepad",
        "start notepad",
        "I want to write something",
        "open a text editor",
        "launch text editor",
        "open word processor",
        "I need to take notes",
        "start writing app",
        "open writing program"
    ],
    
    "open_website": [
        "go to youtube dot com",
        "I want to see google",
        "open the website wikipedia",
        "can you show me amazon",
        "navigate to twitch",
        "open youtube",
        "go to google",
        "visit facebook",
        "open instagram",
        "browse to reddit",
        "show me twitter",
        "go to linkedin",
        "open netflix",
        "visit github",
        "browse stackoverflow",
        "go to the web",
        "open my browser",
        "I want to browse the internet"
    ],
    
    "get_time": [
        "what is the time",
        "tell me the time please",
        "what's the time right now",
        "do you have the time",
        "current time",
        "what time is it",
        "can you tell me the time",
        "show me the time",
        "I need to know the time",
        "what's the current time",
        "give me the time",
        "check the time",
        "time please",
        "what hour is it",
        "show current time"
    ],
    
    "shutdown_computer": [
        "please shut down my computer",
        "I want to turn off the pc",
        "initiate the shutdown sequence",
        "power down everything",
        "turn off this machine",
        "shutdown the computer",
        "turn off my pc",
        "power off the system",
        "shut down now",
        "turn off computer",
        "power down the machine",
        "shut this down",
        "turn everything off",
        "I want to shutdown",
        "close everything down"
    ],
    
    "greeting": [
        "hello there assistant",
        "hey how are you",
        "hi good morning",
        "nice to meet you",
        "hey bot",
        "hello",
        "hi there",
        "good morning",
        "good afternoon",
        "good evening",
        "how are you doing",
        "what's up",
        "hey there",
        "hi assistant",
        "greetings"
    ],
    
    # Expanded None intent with more diverse examples
    "None": [
        "and that's how it is",
        "I was thinking about the weather",
        "what is the color of the sky",
        "my favorite food is pizza",
        "the dog is barking outside",
        "this is just a random sentence",
        "I need to do laundry later",
        "remember to buy milk",
        "how does a car engine work",
        "the quick brown fox jumps over the lazy dog",
        "I like to read books",
        "the weather is nice today",
        "I'm feeling tired",
        "cats are interesting animals",
        "mathematics is complicated",
        "I enjoy listening to music",
        "the sky is blue",
        "I had lunch earlier",
        "my car needs gas",
        "the movie was entertaining",
        "I should exercise more",
        "coffee tastes good",
        "the sun is shining",
        "I'm thinking about vacation",
        "work was busy today",
        "traffic was heavy",
        "I need to call my friend",
        "the book was interesting",
        "I like chocolate",
        "the game was fun",
        "I should go to bed early"
    ]
}